### ISSUE TITLE
Running CMake to install the packages failing

### ISSUE THREAD

**Issue by schoonhovenrichard** [jwbuurlage/slicevis#10]
Hello,

I am trying to install Recast3D by following the steps outlined here:

https://cicwi.github.io/RECAST3D/live_software_stack/

When compiling (GCC 9.1.1) I get several errors due to Wfatal-errors and Werror being turned on.

""
RECAST3D/ext/eigen/Eigen/src/Core/CwiseBinaryOp.h:105:49: error: implicitly-declared ‘Eigen::Block<const Eigen::Matrix<float, -1, 3>, 1, 3, false>::Block(const Eigen::Block<const Eigen::Matrix<float, -1, 3>, 1, 3, false>&)’ is deprecated [-Werror=deprecated-copy]
  105 |       : m_lhs(aLhs), m_rhs(aRhs), m_functor(func)
""
and
""
RECAST3D/include/modules/geometry.hpp:31:29: error: redundant move in return statement [-Werror=redundant-move]
   31 |             return std::move(packet);
      |                    ~~~~~~~~~^~~~~~~~
compilation terminated due to -Wfatal-errors.
""

when disabling both it compiles fine. In short I got it working but maybe these flags should be removed?

Kind regards,

Richard

**Comment by jwbuurlage** [comment]
I don’t think the response to getting warnings should be to ignore the warnings, we should in general fix the code instead. 

In this case, it seems like `packet`is already an rvalue reference so the cast by `std::move` isn’t doing anything. We should remove the move. 

The issue in Eigen is upstream, I guess in c++20 the rules for implicitly declared copy constructors changed and they still have to adjust. I normally whitelist external dependencies for warnings by using them as system includes, so this should also be done for Eigen.

**Comment by jwbuurlage** [comment]
Actually, it’s probably because of mandatory move elision that the explicit move is no longer necessary since C++17:

https://en.cppreference.com/w/cpp/language/copy_elision#Mandatory_elision_of_copy.2Fmove_operations

**Comment by wjp** [comment]
I removed the relevant moves in cab5a9c47dd30bd8ae1f0d06822f5f85495ab831 . Tested builds with gcc 8.2.0 and 9.2.0.
